### ISSUE TITLE
Boolean values returned from Grasshopper are boxed in to an object with a "value" key

### ISSUE THREAD

**Issue by Browncoat** [Solid-Interactive/grasshopper-core-nodejs#67]
**Currently**
```javascript
"featured": {
            "value": true
        }
```

It would be less confusing if it just returned the value...

**Requested**
```javascript
"featured": true
```

**Comment by pajtai** [comment]
This is because you named the "value" for your checkbox "value" and you called the checkbox group "featured"


I would name the checkbox group "config" and name the "value" "featured" which would give you a more naturel:

```json
"fields" : {
  "config" : {
    "featured" : true
  }
}
```
