### ISSUE TITLE
Cannot View Files Added as Part of Content

### ISSUE THREAD

**Issue by erwintj** [Solid-Interactive/grasshopper-core-nodejs#85]
I've created a custom content type 'Data' with field 'Video', and created content where I uploaded an .mp4 file. However, I'm never actually able to view the video. The furthest path set up is ('/node/:nodeid/assets/:filename') which returns video "url": as "http://localhost:3000/57dac1ab543dd1044dcbd6ed/180178618.hd.mp4" in Postman and a 401 in browser. So, I'm able to see where the video is but never able to reach it in order to view it. Any help on if there is a node where I'd be able to watch the video or if there are a few steps I'm missing would be greatly appreciated!

**Comment by travism** [comment]
Hello, are you saying that your video doesn't display in the administration site? Or when you request it through the grasshopper API?

**Comment by erwintj** [comment]
The video doesn't display in either. In the admin site if I click 'View Selected File' and then 'Open' it opens a new tab with the same url given above which displays File not Found. If I click 'View Selected File' and then 'Download' it fails and says no file. If I change the given url to the format ('/node/:nodeid/assets/:filename') I receive a 401 error. If I try to reach the file through the API with format ('/node/:nodeid/assets/:filename') in Postman via GET with Authorization passed in the header,  I receive the same url: http://localhost:3000/57dac1ab543dd1044dcbd6ed/180178618.hd.mp4, along with size & lastmodified.

**Comment by erwintj** [comment]
It looks like the problem is that the url is given in the format: /nodeid/filename & the route set up to view it is /node/nodeid/assets/filename.

**Comment by travism** [comment]
Oh, I see. It really sounds like your public folder is not linked correctly.

You should have set up a `public` path for all of your assets to be uploaded and served through express. 

Something like
```
app.use(express.static(__dirname + '/public'));
```

And for the configuration see the config section in the documentation:

https://solid-interactive.github.io/grasshopper-core-nodejs/documentation.html#gettingstarted

Now, your assets should not need the API to serve them. It also sounds like your API route and your asset route might be going to the same place causing a conflict. For the `assets` config if it is set to '/' as the path try changing it to '/assets' or something different than the default API routes.

**Comment by erwintj** [comment]
I set up my project using grasshopper fly, and so I had app.use(express.static(__dirname + '/public')); in the index.js file already. In the config file the "urlbase" was set to "http://locahost:3000" when I started. I changed it to "http://localhost:3000" to get the admin running, then just now I added /assets/ to make it "http://localhost3000/assets/" which fixed the issue I was having. Thanks!

**Comment by travism** [comment]
Great, glad that fixed the issue.
