### ISSUE TITLE
the same tests sometimes pass or fail on travis ci

### ISSUE THREAD

**Issue by pajtai** [Solid-Interactive/grasshopper-core-nodejs#92]
str: rerun the tests via the ui
seems to be isolated to a few tests, guessing some sort of timing issue

**Comment by travism** [comment]
From my analysis earlier, I found that it is not actually isolated to tests and it is intermittent. I can replicate this pretty regularly locally in addition to travis-ci. 

It could be a delay in writing data to the database and then immediately reading from it.

**Comment by pajtai** [comment]
This should be fixed in https://github.com/Solid-Interactive/grasshopper-core-nodejs/commit/7a7ad2de7a1aafa1f858d81ec70d560524609282 .

Made sure grunt data:load is called before starting gh, and also cleaned up some place in gh, where simply requiring in gh was doing work.

**Comment by travism** [comment]
Nicely done sir. That was bugging me the last time I was working on this.
